# Generated by Django 3.0.5 on 2020-04-20 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gloxon_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='GLoxon Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='gloxon_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gloxon ID'),
        ),
    ]
