# Generated by Django 3.0.5 on 2020-04-03 11:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='payment response'),
        ),
    ]
