# Generated by Django 3.0.5 on 2020-04-03 14:10

from django.db import migrations, models
import storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_auto_20200403_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='preview_image',
            field=models.FileField(blank=True, storage=storage_backend.PreviewImageStorage(), upload_to='', verbose_name='preview image'),
        ),
    ]
