# Generated by Django 3.0.5 on 2020-04-21 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_auto_20200420_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to=settings.AUTH_USER_MODEL),
        ),
    ]
