# Generated by Django 3.0.5 on 2020-04-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0003_software_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rave_public_key',
            field=models.CharField(blank=True, help_text='Plublic key obtained from https://bit.ly/3aHzeFJ. NB: This link contains a referral id.', max_length=255, verbose_name='Flutterwave Public Key'),
        ),
    ]
