# Generated by Django 3.0.5 on 2020-04-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0004_user_rave_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rave_secret_key',
            field=models.CharField(blank=True, help_text='Optional: If provided, we will verify payments before marking them as verified otherwise, we simply mark as verified..', max_length=255, verbose_name='Flutterwave Secret Key'),
        ),
    ]
